// Build the executed record: the uploaded PDF with a signature certificate page appended.
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { AuditEvent, SignatureRequest } from "../types.ts";

const TEAL = rgb(0, 0.302, 0.263);
const INK = rgb(0.106, 0.106, 0.106);
const BODY = rgb(0.39, 0.39, 0.39);

export async function buildSignedPdf(input: {
  originalPdf: Buffer;
  request: SignatureRequest;
  auditEvents: AuditEvent[];
  pdfSha256: string;
  completedAt: string;
}): Promise<Buffer> {
  const pdf = await PDFDocument.load(input.originalPdf, { ignoreEncryption: true });
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const page = pdf.addPage([612, 792]);
  const margin = 54;
  let y = 792 - margin;

  const line = (text: string, size = 10, font = regular, color = INK, gap = 6) => {
    // naive wrap at ~95 chars for the body font size
    const maxChars = Math.floor((612 - margin * 2) / (size * 0.5));
    const words = text.split(" ");
    let current = "";
    const flush = () => {
      page.drawText(current, { x: margin, y, size, font, color });
      y -= size + gap;
      current = "";
    };
    for (const word of words) {
      if ((current + " " + word).trim().length > maxChars) flush();
      current = (current + " " + word).trim();
    }
    if (current) flush();
  };

  page.drawRectangle({ x: 0, y: 792 - 70, width: 612, height: 70, color: TEAL });
  page.drawText("AUTOMATION ARCHITECTURE AI", { x: margin, y: 792 - 30, size: 9, font: bold, color: rgb(0.902, 1, 0.169) });
  page.drawText("SIGNATURE CERTIFICATE", { x: margin, y: 792 - 52, size: 16, font: bold, color: rgb(0.976, 0.969, 0.949) });
  y = 792 - 100;

  line(input.request.title, 13, bold, TEAL, 10);
  line(`Request ID: ${input.request.id}`, 9, regular, BODY, 4);
  line(`Completed: ${input.completedAt} (UTC)`, 9, regular, BODY, 4);
  line(`Original document SHA-256: ${input.pdfSha256}`, 9, regular, BODY, 4);
  line(`Record fingerprint (document + parties): ${input.request.documentSha256}`, 9, regular, BODY, 14);

  const signers = [...input.request.signers].sort((a, b) => a.order - b.order);
  for (const signer of signers) {
    const signed = input.auditEvents.find((e) => e.signerId === signer.id && e.type === "signed");
    const viewed = input.auditEvents.filter((e) => e.signerId === signer.id && e.type === "viewed").at(0);
    const sent = input.auditEvents.filter((e) => e.signerId === signer.id && e.type === "sent").at(0);
    const typedName = String(signed?.detail?.typedLegalName ?? signer.name);

    y -= 4;
    page.drawLine({ start: { x: margin, y }, end: { x: 612 - margin, y }, thickness: 0.5, color: rgb(0.847, 0.847, 0.847) });
    y -= 18;
    line(`SIGNER ${signer.order + 1}: ${signer.name.toUpperCase()}`, 11, bold, INK, 8);
    line(`Email: ${signer.email}`, 10, regular, INK, 4);
    line(`Signed as (typed legal name): ${typedName}`, 10, regular, INK, 4);
    line(`Signed at: ${signer.signedAt ?? ""} (UTC)`, 10, regular, INK, 4);
    if (sent) line(`Invitation sent: ${sent.occurredAt} to ${signer.email}`, 9, regular, BODY, 3);
    if (viewed) line(`First viewed: ${viewed.occurredAt}  IP ${viewed.ip ?? "n/a"}`, 9, regular, BODY, 3);
    if (signed) line(`Signature IP ${signed.ip ?? "n/a"}  User agent: ${signed.userAgent ?? "n/a"}`, 9, regular, BODY, 3);
    line(`Consent to electronic records and signatures: given on the signing page before signing.`, 9, regular, BODY, 10);
  }

  y -= 6;
  line(
    "This certificate was generated by contract.automationarchitecture.ai when the final party signed. Each signer received a single-use signing link at the email address above, reviewed this exact document (verified by SHA-256 fingerprint at the moment of signing), consented to electronic signature, and typed their legal name as their signature. The audit trail is stored in a table that refuses edits and deletions.",
    8,
    regular,
    BODY,
    3,
  );

  return Buffer.from(await pdf.save());
}
